Completed prep JavaScript variables exercise.
samlee0258/prep-0722-code-solutions pull request #10
Opened 2022-08-09 07:34 UTC by samlee0258

<img width="1440" alt="Screen Shot 2022-08-09 at 12 31 43 AM" src="https://user-images.githubusercontent.com/110208589/183591439-1031f255-af17-49d3-8342-f39800db13b1.png">

2022-08-09 15:54 UTC, thebearingedge requested changes

2022-08-09 15:54 UTC, thebearingedge commented on prep-javascript-variables/index.html
> +    var nothing = 'null';
Hi Samuel, be sure to leave off the quotes for numbers and null so that the JavaScript engine doesn't interpret them as strings.

2022-08-10 01:30 UTC, samlee0258 commented on prep-javascript-variables/index.html
> +    var nothing = 'null';
<img width="634" alt="Screen Shot 2022-08-09 at 6 29 31 PM" src="https://user-images.githubusercontent.com/110208589/183790620-ad5e389a-683b-4c65-b4a0-83420e899978.png">

2022-08-10 01:45 UTC, thebearingedge approved these changes

2022-08-10 01:50 UTC, merged