Completed prep JavaScript arrays exercise.
samlee0258/prep-0722-code-solutions pull request #12
Opened 2022-08-09 08:42 UTC by samlee0258

<img width="827" alt="Screen Shot 2022-08-09 at 1 39 48 AM" src="https://user-images.githubusercontent.com/110208589/183605379-1c524404-8e6c-4560-8680-baacad1e2b34.png">

2022-08-09 16:10 UTC, thebearingedge requested changes

2022-08-09 16:10 UTC, thebearingedge commented on prep-javascript-arrays/main.js
> +console.log('The last element of the array  is:', lastElement);
Hi Samuel, for this one we want to subtract `1` from the `languages.length` to calculate the last index.

```js
var lastElement = languages[languages.length - 1];
```

2022-08-10 01:38 UTC, samlee0258 commented on prep-javascript-arrays/main.js
> +console.log('The last element of the array  is:', lastElement);
<img width="614" alt="Screen Shot 2022-08-09 at 6 38 07 PM" src="https://user-images.githubusercontent.com/110208589/183791515-e7de1136-9a38-4d6a-9dff-3a8aa9575446.png">

2022-08-10 01:46 UTC, thebearingedge approved these changes

2022-08-10 01:51 UTC, merged